version: '3'
services:
  worker1:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_MASTER_SEND_TOPIC=${KAFKA_MASTER_SEND_TOPIC}
      - KAFKA_WORKER_SEND_TOPIC=${KAFKA_WORKER_SEND_TOPIC}
      - KAFKA_WORKER_CONNECTION_TOPIC=${KAFKA_WORKER_CONNECTION_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}
      - CLIENT_DATA_PATH=${CLIENT_DATA_PATH}
      - SMB_HOST=${SMB_HOST}
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_PORT=${SMB_PORT}
      - SHODAN_COOKIE=${SHODAN_COOKIE}
      - VM_ID=VM1
      - WORKER_NUMBER=1
    privileged: true

  worker2:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_MASTER_SEND_TOPIC=${KAFKA_MASTER_SEND_TOPIC}
      - KAFKA_WORKER_SEND_TOPIC=${KAFKA_WORKER_SEND_TOPIC}
      - KAFKA_WORKER_CONNECTION_TOPIC=${KAFKA_WORKER_CONNECTION_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}
      - CLIENT_DATA_PATH=${CLIENT_DATA_PATH}
      - SMB_HOST=${SMB_HOST}
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_PORT=${SMB_PORT}
      - SHODAN_COOKIE=${SHODAN_COOKIE}
      - VM_ID=VM2
      - WORKER_NUMBER=2
    privileged: true

  worker3:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_MASTER_SEND_TOPIC=${KAFKA_MASTER_SEND_TOPIC}
      - KAFKA_WORKER_SEND_TOPIC=${KAFKA_WORKER_SEND_TOPIC}
      - KAFKA_WORKER_CONNECTION_TOPIC=${KAFKA_WORKER_CONNECTION_TOPIC}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_AUTO_OFFSET_RESET=${KAFKA_AUTO_OFFSET_RESET}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS}
      - CLIENT_DATA_PATH=${CLIENT_DATA_PATH}
      - SMB_HOST=${SMB_HOST}
      - SMB_USER=${SMB_USER}
      - SMB_PASS=${SMB_PASS}
      - SMB_PORT=${SMB_PORT}
      - SHODAN_COOKIE=${SHODAN_COOKIE}
      - VM_ID=VM3
      - WORKER_NUMBER=3
    privileged: true 